### ISSUE TITLE
Is the google analytics measurement ID correct?

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/AI_for_software#92]
https://github.com/fhdsl/AI_for_software/blob/cdc03d537d93c87c7b4bcfb5694b4b2ca74f685c/GA_Script.Rhtml#L16

I'm seeing this ID online: G-Q4LSK62HQ2

![image](https://github.com/fhdsl/AI_for_software/assets/15618412/a3d1f7f5-1512-468f-99c9-c80a20c25b50)

@cansavvy

**Comment by cansavvy** [comment]
Oh yes. This is the incorrect tag. We should switch it. Good catch. Sorry about that.
